config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "pages#home"
  get "pages/home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by uptime monitors like UptimeRobot.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/property.rb
class Property < ApplicationRecord
    validates :name, presence: true, uniqueness: true
    validates :headline, presence: true
    validates :description, presence: true
    validates :address_1, presence: true
    validates :city, presence: true
    validates :state, presence: true
    validates :country, presence: true

    monetize :price_cents, allow_nil: true

    has_many_attached :images
    has_many :reviews, dependent: :destroy

    def update_average_rating
        average_rating = reviews.average(:final_rating);
        update_column(:average_final_rating, average_rating)
    end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :property, counter_cache: true

  validates :content, presence: :true
  validates :cleanliness_rating, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 } 
  validates :accuracy_rating, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 } 
  validates :checkin_rating, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 } 
  validates :communication_rating, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 } 
  validates :location_rating, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 } 
  validates :value_rating, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 } 

  after_commit :update_final_rating, on: [:create, :update]
  after_commit :update_property_average_rating, on: [:create, :update, :destroy]

  def update_final_rating
    total_points = cleanliness_rating + 
      accuracy_rating + 
      checkin_rating + 
      communication_rating + 
      location_rating + 
      value_rating

    update_column(:final_rating, total_points.to_f / 6)
  end

  def update_property_average_rating
    property.update_average_rating
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @properties = Property.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Airbnb | Vacation rentals, cabins, beach houses, & more" %></title>
    <%# favicon %>
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"
    />

    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
  </head>

  <body>
    <%= render "shared/header" %>
      <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="bg-white">
  <%# TODO: Show empty page state %>
  <div class="mx-auto max-w-2xl px-4 sm:px-6 sm:py-8 lg:max-w-7xl lg:px-8">
    <div class="mt-6 grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-4 xl:gap-x-8">
      <% @properties.each_with_index do |property, index| %>
        <%= render 'properties/property_item', property: property, minimal_details: false %>
      <% end %>
    </div>
  </div>
</div>

app/views/properties/_property_item.html.erb
<%= link_to "#" do %>
  <div class="group relative cursor-pointer ">
    <div class="relative overflow-hidden rounded-md bg-gray-200">
      <div class="swiper">
        <!-- Additional required wrapper -->
        <div class="swiper-wrapper">
          <div style="aspect-ratio: 1 / 1; width: 100%;">
                      <!-- Slider main container -->
          <div class="swiper aspect-h-1 aspect-w-1 w-full overflow-hidden rounded-md bg-gray-200">
            <!-- Additional required wrapper -->
            <div class="swiper-wrapper">
              <% property.images.each do |image| %>
                <%= image_tag image, class:"swiper-slide h-full w-full object-cover object-center lg:h-full lg:w-full" %>
              <% end %>
            </div>
            
            <!-- If we need navigation buttons -->
            <div class="swiper-button-prev"></div>
            <div class="swiper-button-next"></div>
          </div>
          </div>
        
        <%# TODO: Swiper buttons are not working %>
        <!-- If we need navigation buttons -->
        <div class="swiper-button-prev"></div>
        <div class="swiper-button-next"></div>
      </div>

      <div class="absolute z-[2] right-0 top-0 m-4">
        <svg xmlns="http://www.w3.org/2000/svg" 
          viewBox="0 0 32 32" 
          aria-hidden="true" 
          role="presentation" 
          focusable="false"
          class="block h-6 w-6 stroke-white stroke-2 fill-none"
          style="overflow: visible;"
          >
            <path d="M16 28c7-4.73 14-10 14-17a6.98 6.98 0 0 0-7-7c-1.8 0-3.58.68-4.95 2.05L16 8.1l-2.05-2.05a6.98 6.98 0 0 0-9.9 0A6.98 6.98 0 0 0 2 11c0 7 7 12.27 14 17z"></path>
        </svg>
      </div>
    </div>
    <div class="mt-2">
      <div class="flex justify-between">
        <h3 class="text-base font-medium text-gray-700 line-clamp-1">
          <%= property.name %>
        </h3>
        <p class="flex items-center text-sm font-light">
          <svg
            class="mr-1 block w-3 h-3 fill-current"
            xmlns="http://www.w3.org/2000/svg" 
            viewBox="0 0 32 32" 
            aria-hidden="true" 
            role="presentation" 
            focusable="false" 
          >
            <path fill-rule="evenodd" d="m15.1 1.58-4.13 8.88-9.86 1.27a1 1 0 0 0-.54 1.74l7.3 6.57-1.97 9.85a1 1 0 0 0 1.48 1.06l8.62-5 8.63 5a1 1 0 0 0 1.48-1.06l-1.97-9.85 7.3-6.57a1 1 0 0 0-.55-1.73l-9.86-1.28-4.12-8.88a1 1 0 0 0-1.82 0z"></path>
          </svg>
                          <%= property.average_final_rating ? property.average_final_rating.round(2) : "New" %>
        </p>
      </div>
      <%# TODO: Add distance from property based on location %>
      <% if defined?(minimal_details) && minimal_details %>
        <p class="mt-0.5 text-sm text-gray-500"><%= property.headline %></p>
      <% else %>
        <p class="mt-0.5 text-sm text-gray-500"><%= property.city %>, <%= property.state %></p>
                    <p class="mt-0.5 text-sm font-light text-black">
              <span class="font-medium"><%= humanized_money_with_symbol(property.price) %></span> night
            </p>
      <% end %>
    </div>
  </div>
<% end %>